title: Kranti Cares
description: >
 Kranti is passionate about saving the environment by creating awareness
 and reducing carbon footprint. Being an active runner and a marathoner,
 she takes part in plogging to clear the streets during runs and clear trekking pathways.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "kranticares.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kranti Salvi # add your name
author-img: software.jpg # add your photo
about-author: Kranti is passionate about saving the environment by creating awareness and reducing carbon footprint. Being an active runner and a marathoner, she takes part in plogging to clear the streets during runs and clear trekking pathways. # add description
social-twitter: krantis # add your Twitter handle
social-facebook: krantisalvi # add your Facebook handle
social-github: # add your Github handle
social-linkedin: kranti-salvi-28733513 # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
